TABLE_SCHEMA                                                                                                                     TABLE_NAME         
-------------------------------------------------------------------------------------------------------------------------------- --------------------------------------------------------------------------------------------------------------------------------
dbo                                                                                                                              DebtorContactCalcs 
dbo                                                                                                                              DebtorTagsCalcs    
dbo                                                                                                                              Expenses           
dbo                                                                                                                              HolidayTranslations
dbo                                                                                                                              WorkflowTemplateStages
dbo                                                                                                                              WorkflowTemplates  
dbo                                                                                                                              Workflows          
dbo                                                                                                                              BankAccount        
dbo                                                                                                                              DebtAgreementTerminations
dbo                                                                                                                              WorkflowStages     
dbo                                                                                                                              Administrator      
dbo                                                                                                                              Debtor             
dbo                                                                                                                              EntityTagChangeSets
dbo                                                                                                                              DebtAgreementCompletions
dbo                                                                                                                              Emails             
dbo                                                                                                                              EntityTags         
dbo                                                                                                                              DebtorCalcs        
dbo                                                                                                                              EntityTagChangeSetTags
dbo                                                                                                                              DebtAgreement      
dbo                                                                                                                              UserAdministrators 
dbo                                                                                                                              RepaymentScheduleChanges
dbo                                                                                                                              WorkflowTemplateTasks
dbo                                                                                                                              Creditor           
dbo                                                                                                                              WorkflowTasks      
dbo                                                                                                                              DebtorCreditors    
dbo                                                                                                                              DebtorRepayment    
dbo                                                                                                                              User               
dbo                                                                                                                              EmailTemplateAdministratorRestrictions
dbo                                                                                                                              DebtAgreementDefaults
dbo                                                                                                                              Settings           
dbo                                                                                                                              DividendCycles     
dbo                                                                                                                              SmsTemplateAdministratorRestrictions
dbo                                                                                                                              SmsTemplates       
dbo                                                                                                                              RealisationsChargeRate
dbo                                                                                                                              NoteTemplateAdministratorRestrictions
dbo                                                                                                                              ContactLogAttachments
dbo                                                                                                                              Postcodes          
dbo                                                                                                                              ContactLogSms      
dbo                                                                                                                              EmailTemplateAttachments
dbo                                                                                                                              ThreeMonthsArrearsRecommendations
dbo                                                                                                                              RelatedCreditors   
dbo                                                                                                                              __MigrationHistory 
dbo                                                                                                                              BankTransaction    
dbo                                                                                                                              SharedDebtLinks    
dbo                                                                                                                              RelatedCreditorDebtAgreementProposals
dbo                                                                                                                              Payment            
dbo                                                                                                                              EmploymentJobs     
dbo                                                                                                                              PaymentLine        
dbo                                                                                                                              DebtAgreementProposals
dbo                                                                                                                              Assets             
dbo                                                                                                                              LiabilitySecurities
dbo                                                                                                                              AuditLogFields     
dbo                                                                                                                              Liabilities        
dbo                                                                                                                              AuditLogs          
dbo                                                                                                                              Businesses         
dbo                                                                                                                              ArrearsHolidays    
dbo                                                                                                                              Companies          
dbo                                                                                                                              ExternalPaymentSources
dbo                                                                                                                              CompanySoldShares  
dbo                                                                                                                              AutomatedRepaymentRuns
dbo                                                                                                                              DebtAgreementCorrespondence
dbo                                                                                                                              AutomatedRepayments
dbo                                                                                                                              CorrespondenceReferences
dbo                                                                                                                              PaymentSources     
dbo                                                                                                                              ExpenseItems       
dbo                                                                                                                              IncomeItems        
dbo                                                                                                                              LiabilityNonDividends
dbo                                                                                                                              OriginHomeLanguages
dbo                                                                                                                              Properties         
dbo                                                                                                                              ProposalPayments   
dbo                                                                                                                              NoteTemplates      
dbo                                                                                                                              Trusts             
dbo                                                                                                                              AuditLogEntityNames
dbo                                                                                                                              AuditLogFieldNames 
dbo                                                                                                                              DebtorDetailsChanges
dbo                                                                                                                              EmailAccount       
dbo                                                                                                                              AutomatedRepaymentNotifications
dbo                                                                                                                              ExportTemplateFields
dbo                                                                                                                              ExportTemplates    
dbo                                                                                                                              BankAccountSources 
dbo                                                                                                                              CreditorContacts   
dbo                                                                                                                              PaymentSourceSecureDetails
dbo                                                                                                                              ReminderCategories 
dbo                                                                                                                              UserGroups         
dbo                                                                                                                              ContactLogPriority 
dbo                                                                                                                              DebtorOtherNames   
dbo                                                                                                                              ContactLogSendType 
dbo                                                                                                                              ContactLog         
dbo                                                                                                                              EmailTemplates     
dbo                                                                                                                              UserPermissions    
dbo                                                                                                                              ArrearsPeriods     
dbo                                                                                                                              UserGroupUsers     
dbo                                                                                                                              PaymentMethods     
dbo                                                                                                                              ContactLogFiles    
dbo                                                                                                                              DebtAgreementVariations
dbo                                                                                                                              ContactLogNotes    
dbo                                                                                                                              LiabilityChanges   
dbo                                                                                                                              EmailData          
dbo                                                                                                                              ExpensePresets  